'use strict';
const cfg=window.RADAR_CONFIG||{};let db=null,user=null,profile=null,map=null,userLocation=null,userMarker=null,markers=new Map(),installPrompt=null,authMode='login';
const $=id=>document.getElementById(id);const qs=s=>document.querySelector(s);const qsa=s=>[...document.querySelectorAll(s)];
function msg(el,text,type='error'){el.className=type;el.textContent=text||''}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function configured(){return cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('SEU-PROJETO')&&cfg.SUPABASE_PUBLISHABLE_KEY&&!cfg.SUPABASE_PUBLISHABLE_KEY.includes('SUA_CHAVE')}
function initDb(){if(!configured()){console.warn('Supabase não configurado');return}db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
function initMap(){map=L.map('map',{zoomControl:false}).setView([53.3498,-6.2603],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map)}
function showScreen(name){qsa('.screen').forEach(x=>x.classList.remove('active'));$('screen-'+name).classList.add('active');qsa('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));if(name==='map')setTimeout(()=>map.invalidateSize(),80);if(name==='alerts')loadAlerts();if(name==='profile')renderProfile()}
function openModal(id){$(id).classList.remove('hidden')}function closeModal(id){$(id).classList.add('hidden')}
function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS não disponível neste aparelho.'));navigator.geolocation.getCurrentPosition(p=>{userLocation={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};resolve(userLocation)},e=>reject(new Error(e.code===1?'Permissão de localização negada.':'Não foi possível obter a localização.')),{enableHighAccuracy:true,timeout:12000,maximumAge:30000})})}
async function locate(){const p=await getPosition();if(userMarker)userMarker.setLatLng(p);else userMarker=L.circleMarker(p,{radius:9,color:'#fff',weight:3,fillColor:'#23f36b',fillOpacity:1}).addTo(map).bindPopup('Você está aqui');map.setView(p,16);return p}
function distance(a,b){const R=6371000,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function publicCoord(n){return Math.round(n*1000)/1000}
function requireAuth(){if(!user){openModal('authModal');throw new Error('Entre na sua conta para continuar.')}}
async function refreshSession(){if(!db)return renderProfile();const {data}=await db.auth.getSession();user=data.session?.user||null;if(user){const {data:p}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=p||null}renderProfile()}
function renderProfile(){$('profileGuest').classList.toggle('hidden',!!user);$('profileUser').classList.toggle('hidden',!user);if(user){$('profileName').textContent=profile?.display_name||user.user_metadata?.display_name||'Rider';$('profileEmail').textContent=user.email||'';$('adminLink').classList.toggle('hidden',profile?.role!=='admin')}}
async function loadAlerts(){if(!db){$('alertsList').innerHTML='<div class="notice">Conecte o Supabase em config.js para carregar alertas reais.</div>';return}const {data,error}=await db.from('alerts').select('id,category,description,occurred_at,is_ongoing,latitude_public,longitude_public,status,expires_at,created_at,confirmations_count').eq('status','active').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(100);if(error){$('alertsList').innerHTML='<div class="error">'+esc(error.message)+'</div>';return}renderAlerts(data||[])}
function categoryIcon(c){return({intimidacao:'⚠️',roubo:'🚨',grupo_hostil:'👥',via_perigosa:'🛣️',acidente:'⛔',outro:'📍'})[c]||'📍'}
function renderAlerts(list){markers.forEach(m=>m.remove());markers.clear();$('alertsList').innerHTML=list.length?'':'<div class="card muted">Nenhum alerta ativo.</div>';list.forEach(a=>{const when=new Date(a.created_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});const card=document.createElement('div');card.className='card alert-card';card.innerHTML=`<div class="alert-icon">${categoryIcon(a.category)}</div><div><h3>${esc(a.category.replaceAll('_',' '))}</h3><p>${esc(a.description)}</p><div class="meta"><span>${when}</span><span>${a.confirmations_count||0} confirmações</span></div><div class="chips">${a.is_ongoing?'<span class="chip live">Ainda acontecendo</span>':''}<span class="chip">Área aproximada</span></div></div><div class="alert-actions"><button class="primary" data-confirm="${a.id}" data-lat="${a.latitude_public}" data-lng="${a.longitude_public}">Confirmar</button><button class="secondary" data-map="${a.latitude_public},${a.longitude_public}">Ver no mapa</button><button class="danger-btn" data-report="${a.id}">Denunciar</button></div>`;$('alertsList').appendChild(card);const m=L.marker([a.latitude_public,a.longitude_public]).addTo(map).bindPopup(`<b>${esc(a.category)}</b><br>${esc(a.description)}`);markers.set(a.id,m)});qsa('[data-map]').forEach(b=>b.onclick=()=>{const [lat,lng]=b.dataset.map.split(',').map(Number);showScreen('map');map.setView([lat,lng],16)});qsa('[data-report]').forEach(b=>b.onclick=()=>{$('reportedAlertId').value=b.dataset.report;openModal('reportModal')});qsa('[data-confirm]').forEach(b=>b.onclick=()=>confirmAlert(b.dataset.confirm,{lat:+b.dataset.lat,lng:+b.dataset.lng}))}
async function confirmAlert(id,alertPos){try{requireAuth();const p=await getPosition(),d=Math.round(distance(p,alertPos));if(d>2000)throw new Error(`Você está a ${Math.round(d/100)/10} km. Confirmações são permitidas somente até 2 km do alerta.`);const {error}=await db.from('alert_confirmations').insert({alert_id:id,user_id:user.id,distance_metres:d});if(error)throw error;alert('Alerta confirmado. Obrigado por ajudar a comunidade.');loadAlerts()}catch(e){alert(e.message.includes('duplicate')?'Você já confirmou este alerta.':e.message)}}
async function publishAlert(e){e.preventDefault();try{requireAuth();const p=await getPosition(),minutes=+$('duration').value;const occurredMap={agora:0,'5_min':5,'15_min':15,'30_min':30,'1_hora':60};const occurred=new Date(Date.now()-occurredMap[$('occurredWhen').value]*60000);const expires=new Date(Date.now()+minutes*60000);const payload={user_id:user.id,category:$('category').value,description:$('description').value.trim(),occurred_at:occurred.toISOString(),is_ongoing:$('ongoing').checked,latitude_private:p.lat,longitude_private:p.lng,latitude_public:publicCoord(p.lat),longitude_public:publicCoord(p.lng),expires_at:expires.toISOString()};const {error}=await db.from('alerts').insert(payload);if(error)throw error;msg($('alertMsg'),'Alerta publicado com localização aproximada.','success');e.target.reset();showScreen('alerts');loadAlerts()}catch(err){msg($('alertMsg'),err.message)}}
async function submitReport(e){e.preventDefault();try{requireAuth();const {error}=await db.from('alert_reports').insert({alert_id:$('reportedAlertId').value,reported_by:user.id,reason:$('reportReason').value,details:$('reportDetails').value.trim()});if(error)throw error;msg($('reportMsg'),'Denúncia enviada para moderação.','success');setTimeout(()=>closeModal('reportModal'),700)}catch(err){msg($('reportMsg'),err.message)}}
async function authSubmit(e){e.preventDefault();if(!db)return msg($('authMsg'),'Configure o Supabase primeiro.');const email=$('authEmail').value.trim(),password=$('authPassword').value;try{if(authMode==='signup'){const {error}=await db.auth.signUp({email,password,options:{data:{display_name:$('authName').value.trim()},emailRedirectTo:cfg.SITE_URL}});if(error)throw error;msg($('authMsg'),'Conta criada. Verifique seu e-mail para confirmar.','success')}else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;closeModal('authModal');await refreshSession()}}catch(err){msg($('authMsg'),err.message)}}
async function forgot(){if(!db)return;const email=$('authEmail').value.trim();if(!email)return msg($('authMsg'),'Digite seu e-mail primeiro.');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:cfg.SITE_URL});msg($('authMsg'),error?error.message:'E-mail de redefinição enviado.',error?'error':'success')}
async function shareLocation(copyOnly=false){try{const p=await getPosition(),url=`https://www.google.com/maps?q=${p.lat},${p.lng}`,text=`🚨 Preciso de ajuda. Esta é minha localização atual:\n${url}\n\nEnviado pelo Radar Rider.`;if(copyOnly){await navigator.clipboard.writeText(text);msg($('emergencyMsg'),'Localização copiada.','success')}else{location.href=`https://wa.me/?text=${encodeURIComponent(text)}`}}catch(e){msg($('emergencyMsg'),e.message)}}
async function requestDeletion(){if(!confirm('Deseja solicitar a exclusão da sua conta e dos dados associados?'))return;try{requireAuth();const {error}=await db.from('account_deletion_requests').insert({user_id:user.id,email:user.email});if(error)throw error;alert('Solicitação registrada. A equipe de suporte fará a exclusão segura.')}catch(e){alert(e.message)}}
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').classList.remove('hidden')});const run=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else alert('Android: use o menu do navegador e escolha Instalar app.\niPhone: Safari → Compartilhar → Adicionar à Tela de Início.')};$('installBtn').onclick=run;$('installProfileBtn').onclick=run}
function bind(){qsa('.nav-btn').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));qsa('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('emergencyBtn').onclick=()=>openModal('emergencyModal');$('openAuthBtn').onclick=()=>openModal('authModal');$('newAlertBtn').onclick=()=>showScreen('report');$('locateBtn').onclick=()=>locate().catch(e=>alert(e.message));$('alertForm').onsubmit=publishAlert;$('reportForm').onsubmit=submitReport;$('authForm').onsubmit=authSubmit;$('forgotBtn').onclick=forgot;$('shareWhatsAppBtn').onclick=()=>shareLocation(false);$('copyLocationBtn').onclick=()=>shareLocation(true);$('logoutBtn').onclick=async()=>{await db.auth.signOut();user=null;profile=null;renderProfile()};$('resetPasswordBtn').onclick=async()=>{const {error}=await db.auth.resetPasswordForEmail(user.email,{redirectTo:cfg.SITE_URL});alert(error?error.message:'E-mail enviado.')};$('deleteAccountBtn').onclick=requestDeletion;qsa('.auth-tab').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;qsa('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('nameWrap').classList.toggle('hidden',authMode!=='signup')})}
async function boot(){initDb();initMap();bind();setupInstall();if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js');await refreshSession();await loadAlerts();if(db){db.channel('public-alerts').on('postgres_changes',{event:'*',schema:'public',table:'alerts'},loadAlerts).subscribe();db.auth.onAuthStateChange(()=>setTimeout(refreshSession,0))}}
document.addEventListener('DOMContentLoaded',boot);
